### ISSUE TITLE
`Harte('Bb:(4,#5,b7)')` contains `F-` instead of `F#`

### ISSUE THREAD

**Issue by rubencart** [andreamust/harte-library#30] opened 2024-04-10 12:55 UTC
Contains F- while it should contain F#. Also it would be nice if quality returned augmented (or suspended, but this appears never to be returned by `music21.chord.Chord` anyway).

```python
c = Harte('Bb:(4,#5,b7)')
c.quality
Out[6]: 'other'
c.pitches
Out[7]: 
(<music21.pitch.Pitch B-4>,
 <music21.pitch.Pitch E-5>,
 <music21.pitch.Pitch F-5>,
 <music21.pitch.Pitch A-5>)
```

**Comment by andreamust** [comment] 2024-04-30 12:40
In the current version of the library (`0.4.4`) this chord is correctly parsed:

```python
c = Harte('Bb:(4,#5,b7)')
c.pitches
Out[1]: 
(<music21.pitch.Pitch B-4>, 
 <music21.pitch.Pitch E-5>, 
 <music21.pitch.Pitch F#5>, 
 <music21.pitch.Pitch A-5>)
 ```

Please, consider updating the library to fix this issue.

As for the issue with the `quality` property, we rely on `music21.Chord` module. Therefore, this part of the issue is out of scope for the `harte_library`.

**Closed by andreamust** 2024-04-30 12:40 UTC
Labels: wontfix
